//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantRating.Repository.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewNumber { get; set; }
        public int Rating { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ReviewUser { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int RestaurantId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
